Adding configure switch to disable WebUpdateCheck by default. Useful for distro packages.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1335,6 +1335,8 @@ Optional Features:
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-gcov           enable test coverage with gcov [default=no]
+  --disable-default-webupdatecheck
+                          Disable WebUpdateCheck by default. [default=no]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4250,6 +4252,37 @@ if test "x$gcov" = "xtrue"; then
     CXXFLAGS="$CXXFLAGS -fprofile-arcs -ftest-coverage"
 fi
 
+# configure switch to disable WebUpdateCheck by default
+
+{ echo "$as_me:$LINENO: checking whether to disable WebUpdateCheck by default" >&5
+echo $ECHO_N "checking whether to disable WebUpdateCheck by default... $ECHO_C" >&6; }
+
+# Check whether --enable-default-webupdatecheck was given.
+if test "${enable_default_webupdatecheck+set}" = set; then
+  enableval=$enable_default_webupdatecheck;  case "${enableval}" in
+          yes) disable_webupdatecheck=0 ;;
+          no) disable_webupdatecheck=1 ;;
+          *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-default-webupdatecheck" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-default-webupdatecheck" >&2;}
+   { (exit 1); exit 1; }; } ;;
+          esac
+else
+   disable_webupdatecheck=0
+fi
+
+
+if test "$disable_webupdatecheck" != 0; then
+    cat >>confdefs.h <<\_ACEOF
+#define DISABLE_WEBUPDATECHECK 1
+_ACEOF
+
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
 # Checks for typedefs, structures, and compiler characteristics.
 
 # Check for wxWidgets 2.8.0 or later
@@ -5474,6 +5507,8 @@ fi
 
 { echo "$as_me:$LINENO: checking bzlib in ${BZLIB_HOME}" >&5
 echo $ECHO_N "checking bzlib in ${BZLIB_HOME}... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
 
 BZLIB_OLD_LDFLAGS=$LDFLAGS
 BZLIB_OLD_CPPFLAGS=$CPPFLAGS
